### ISSUE TITLE
Unable to use with the latest LiveView version

### ISSUE THREAD

**Issue by Valian** [underjord/entrace_live_dashboard#1]
Hi @lawik, I just watched your intro to Entrace and wanted to try it out. Just there's a problem, `entrace_live_dashboard` mix.exs requirements are quite tight and doesn't allow to use the latest version of `phoenix_live_view`

Snippet from my mix.exs:

```elixir
  defp deps do
    [
      {:bcrypt_elixir, "~> 3.0"},
      {:phoenix, "~> 1.7"},
      {:phoenix_ecto, "~> 4.4"},
      {:phoenix_html, "~> 3.3"},
      {:phoenix_live_reload, "~> 1.2", only: :dev},
      {:phoenix_live_view, "~> 0.20"},
      {:phoenix_live_dashboard, "~> 0.8"},
      ...
      {:entrace_live_dashboard, "~> 0.1.0"}
    ]
```

`mix deps.get` errors out on:

```
Resolving Hex dependencies...
Resolution completed in 0.105s
Because your app depends on entrace_live_dashboard ~> 0.1.0 which depends on phoenix_live_view ~> 0.19.0, phoenix_live_view ~> 0.19.0 is required.
So, because your app depends on phoenix_live_view ~> 0.20, version solving failed
```

Would it be hard to support live_view ~> 0.20?

**Comment by lawik** [comment]
I have not looked for what would work. Those dep specs are quite accidental. If you try to relax them and it works, send a PR :)

Just clone the repo, modify to your heart's content and reference the dep this way while you figure it out:

```
{:entrace, path: "../entrace"}, # or wherever you clone it
```
